In [2]:
import pandas as pd
import datasets

# load dataframe
ds = datasets.load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()

# alter type to datetime
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

In [21]:
# solution 1

cleaned_df = df.loc[
    (df["job_country"] == "United States") & (df["salary_year_avg"].notna()),
    :
]

cleaned_df.groupby("job_title_short").agg(
    median_salary=("salary_year_avg", "median"),
    min_salary=("salary_year_avg", "min"),
    max_salary=("salary_year_avg", "max"),
    total_job_postings=("job_title_short", "count")
).sort_values(by="median_salary", ascending=False).reset_index()

,job_title_short,median_salary,min_salary,max_salary,total_job_postings
0,Senior Data Scientist,155000.0,55000.0,475000.0,1241
1,Machine Learning Engineer,150000.0,44408.5,315000.0,128
2,Senior Data Engineer,150000.0,45000.0,375000.0,1058
3,Data Scientist,130000.0,30000.0,960000.0,4553
4,Software Engineer,130000.0,48982.0,375000.0,157
5,Data Engineer,125000.0,23496.0,525000.0,2915
6,Cloud Engineer,116100.0,42000.0,221844.0,20
7,Senior Data Analyst,110000.0,35360.0,425000.0,913
8,Business Analyst,90000.0,35000.0,387460.0,431
9,Data Analyst,90000.0,25000.0,375000.0,4350

In [20]:
# solution 2

cleaned_df.groupby("job_title_short")["salary_year_avg"].agg(["median", "min", "max", "count"]).sort_values(by="median", ascending=False).reset_index()

             job_title_short    median      min       max  count
0      Senior Data Scientist  155000.0  55000.0  475000.0   1241
1  Machine Learning Engineer  150000.0  44408.5  315000.0    128
2       Senior Data Engineer  150000.0  45000.0  375000.0   1058
3             Data Scientist  130000.0  30000.0  960000.0   4553
4          Software Engineer  130000.0  48982.0  375000.0    157
5              Data Engineer  125000.0  23496.0  525000.0   2915
6             Cloud Engineer  116100.0  42000.0  221844.0     20
7        Senior Data Analyst  110000.0  35360.0  425000.0    913
8           Business Analyst   90000.0  35000.0  387460.0    431
9               Data Analyst   90000.0  25000.0  375000.0   4350