In [1]:
import pandas as pd
import datasets

ds = datasets.load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()

c:\Users\Felipe Novais\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [8]:
df[["job_title_short", "company_name", "salary_hour_avg"]][:1000]

          job_title_short                     company_name  salary_hour_avg
0    Senior Data Engineer             Boehringer Ingelheim              NaN
1            Data Analyst       Hewlett Packard Enterprise              NaN
2           Data Engineer         ALPHA Augmented Services              NaN
3           Data Engineer     Southwest Research Institute              NaN
4           Data Engineer                  Kristina Daniel              NaN
..                    ...                              ...              ...
995        Data Scientist                     Tremor Video              NaN
996         Data Engineer  Trademark Recruiting/Consulting              NaN
997        Data Scientist                         Deloitte              NaN
998         Data Engineer                Certified Konsult              NaN
999     Software Engineer                               bp              NaN

[1000 rows x 3 columns]

In [24]:
df.loc[
        (df["job_title_short"] == "Data Analyst") & (df["job_work_from_home"] == True) & (df["job_country"] == "Brazil"),
        ["job_title_short", "job_work_from_home", "company_name", "job_country"]
    ]

,job_title_short,job_work_from_home,company_name,job_country
169,Data Analyst,True,Acadia,Brazil
1427,Data Analyst,True,idwall,Brazil
4463,Data Analyst,True,Turing,Brazil
7056,Data Analyst,True,Q4,Brazil
12412,Data Analyst,True,Netvagas,Brazil
...,...,...,...,...
767396,Data Analyst,True,meutudo.,Brazil
772880,Data Analyst,True,Kajae,Brazil
774866,Data Analyst,True,MG INFO | Data Driven Culture,Brazil
777018,Data Analyst,True,Turing,Brazil
777766,Data Analyst,True,Origin,Brazil

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

# 1 - Datetime conversion and new column creation

In [27]:
# check type of job_posted_date column
type(df.loc[0, "job_posted_date"])

str

In [ ]:
# convert job_posted_date column from str to datetime
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

In [32]:
# utilize dt parameter to add new column to the dataset
df["job_posted_month"] = df["job_posted_date"].dt.month

In [34]:
# check new column added
df.loc[:,["job_title_short", "job_posted_date", "job_posted_month"]]

             job_title_short     job_posted_date  job_posted_month
0       Senior Data Engineer 2023-06-16 13:44:15                 6
1               Data Analyst 2023-01-14 13:18:07                 1
2              Data Engineer 2023-10-10 13:14:55                10
3              Data Engineer 2023-07-04 13:01:41                 7
4              Data Engineer 2023-08-07 14:29:36                 8
...                      ...                 ...               ...
785736     Software Engineer 2023-03-13 06:16:16                 3
785737          Data Analyst 2023-03-12 06:18:18                 3
785738      Business Analyst 2023-03-12 06:32:36                 3
785739         Data Engineer 2023-03-12 06:32:15                 3
785740     Software Engineer 2023-03-13 06:16:31                 3

[785741 rows x 3 columns]

# 2 - Order by utilizing sort_values method

In [36]:
# just sorting, selecting columns and printing the result
df.sort_values(by="job_posted_date", ascending=True).loc[
    :,
    ["job_title_short", "job_posted_date"]
]

                  job_title_short     job_posted_date
108804               Data Analyst 2023-01-01 00:00:04
96906                Data Analyst 2023-01-01 00:00:07
98438                Data Analyst 2023-01-01 00:00:22
110290               Data Analyst 2023-01-01 00:00:24
72158         Senior Data Analyst 2023-01-01 00:00:27
...                           ...                 ...
362129              Data Engineer 2023-12-31 23:40:31
351830              Data Engineer 2023-12-31 23:40:31
327439              Data Engineer 2023-12-31 23:40:32
112373        Senior Data Analyst 2023-12-31 23:59:58
90102   Machine Learning Engineer 2023-12-31 23:59:58

[785741 rows x 2 columns]

In [ ]:
# sorting and also applying the sort to the DataFrame itself utilizing the inplace named argument
df.sort_values(by="job_posted_date", ascending=True, inplace=True)

In [40]:
df.head(2)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
108804,Data Analyst,Data Analyst,"New York, NY",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:04,False,False,United States,None,NaN,NaN,Metasys Technologies,"['sql', 'snowflake', 'visio', 'jira', 'conflue...","{'analyst_tools': ['visio'], 'async': ['jira',...",1
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,United States,None,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq...",1

# 3 - Drop columns with labels and axis named parameters, and NaN rows based on subset and axis parameters

In [ ]:
# drop the salary_hour_avg column
df.drop(labels="salary_hour_avg", axis=1, inplace=True)

In [51]:
# drop the NaN salary_year_avg rows
df.dropna(subset=["salary_year_avg"], axis=0, inplace=True)

In [54]:
# filtered result
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,job_posted_month
108883,Data Scientist,Data Scientist,"Calabasas, CA",via Recruit.net,Full-time,False,"California, United States",2023-01-01 00:02:56,False,True,United States,year,110000.0,PlanetArt,"['python', 'sql', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr...",1
334082,Data Engineer,Data Engineer,Argentina,via EchoJobs,Full-time,False,Argentina,2023-01-01 00:06:13,True,False,Argentina,year,65000.0,Spiff,"['python', 'mysql', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'databases': ['mys...",1
365786,Business Analyst,Hospitality Operations Analyst,Anywhere,via Goodwin Recruiting | Job Board,Full-time,True,Georgia,2023-01-01 00:17:55,False,True,United States,year,90000.0,Goodwin Recruiting,"['sql', 'excel', 'powerpoint', 'outlook']","{'analyst_tools': ['excel', 'powerpoint', 'out...",1
366073,Data Analyst,Data Analytics Professional,"Atlanta, GA",via CareerBuilder,Full-time,False,Georgia,2023-01-01 00:17:58,False,False,United States,year,55000.0,Cogent Infotech.,"['sql', 'python', 'numpy', 'pandas', 'seaborn'...","{'analyst_tools': ['excel', 'alteryx', 'tablea...",1
108099,Data Scientist,Lead Data Scientist (Hybrid),"Burnsville, MN",via Recruit.net,Full-time,False,"Illinois, United States",2023-01-01 00:21:09,False,False,United States,year,120531.0,Apple Valley,"['java', 'sql', 'sql server', 'spring']","{'databases': ['sql server'], 'libraries': ['s...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186163,Senior Data Scientist,"Tech Lead / Sr Data Scientist, Product Analyti...","Los Angeles, CA",via LinkedIn,Full-time,False,"California, United States",2023-12-31 15:00:46,False,True,United States,year,271526.5,TikTok,"['sql', 'python', 'r', 'express']","{'programming': ['sql', 'python', 'r'], 'webfr...",12
421728,Data Analyst,Data Analyst - Operations,"Los Angeles, CA",via Indeed,Full-time,False,"California, United States",2023-12-31 16:00:07,False,True,United States,year,72750.0,Wilshire Law Firm Plc,"['sql', 'power bi', 'unity']","{'analyst_tools': ['power bi'], 'other': ['uni...",12
313161,Data Scientist,Data Scientist - Security Clearance Required,"Newport News, VA",via IT JobServe,Full-time,False,Georgia,2023-12-31 17:31:57,False,False,United States,year,114062.5,Leidos,"['python', 'r', 'sql', 'pandas', 'numpy']","{'libraries': ['pandas', 'numpy'], 'programmin...",12
336301,Data Scientist,Data scientist,"Dallas, TX",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:22,False,True,Sudan,year,162500.0,Cognizant Technology Solutions,"['python', 'nosql']","{'programming': ['python', 'nosql']}",12
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",12

In [ ]:
# further filtering
df = df.loc[
    df["job_country"] == "Brazil",
    :
]

In [61]:
df.drop(labels=["job_via"], axis=1, inplace=True)

C:\Users\Felipe Novais\AppData\Local\Temp\ipykernel_20584\1687842243.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(labels=["job_via"], axis=1, inplace=True)

In [63]:
df.drop(labels="search_location", axis=1, inplace=True)

C:\Users\Felipe Novais\AppData\Local\Temp\ipykernel_20584\1278902204.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(labels="search_location", axis=1, inplace=True)

In [67]:
df.drop(labels=["job_schedule_type"], axis=1, inplace=True)

C:\Users\Felipe Novais\AppData\Local\Temp\ipykernel_20584\3741093682.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(labels=["job_schedule_type"], axis=1, inplace=True)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 374352 to 507704
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        61 non-null     object
 1   job_title              61 non-null     object
 2   job_location           61 non-null     object
 3   job_work_from_home     61 non-null     bool
 4   job_posted_date        61 non-null     datetime64[ns]
 5   job_no_degree_mention  61 non-null     bool
 6   job_health_insurance   61 non-null     bool
 7   job_country            61 non-null     object
 8   salary_rate            61 non-null     object
 9   salary_year_avg        61 non-null     float64
 10  company_name           61 non-null     object
 11  job_skills             58 non-null     object
 12  job_type_skills        58 non-null     object
 13  job_posted_month       61 non-null     int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(8)
memory usage: 5.7+ KB