In [45]:
import pandas as pd
import datasets

# Data load
ds = datasets.load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()

# Data cleanup
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

1 - Basic statistical functions

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [4]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [ ]:
# unique values in a column
df["job_title_short"].unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [ ]:
# median of a numeric column
df["salary_year_avg"].median()

np.float64(115000.0)

In [10]:
# minimal value of a column, max also exists
df["salary_year_avg"].min()

np.float64(15000.0)

In [13]:
# idxmin() method returns the index of the minimum value, that can then be utilized with iloc
min_salary_id = df["salary_year_avg"].idxmin()
df.iloc[min_salary_id][:]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

# 2 - groupby method

In [15]:
# 
df.groupby("job_title_short")["salary_year_avg"].median()

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

In [24]:
df.groupby("job_title_short")["salary_year_avg"].median().reset_index().sort_values(by="salary_year_avg", ascending=False)

             job_title_short  salary_year_avg
8      Senior Data Scientist         155500.0
7       Senior Data Engineer         147500.0
4             Data Scientist         127500.0
3              Data Engineer         125000.0
6        Senior Data Analyst         111175.0
5  Machine Learning Engineer         106415.0
9          Software Engineer          99150.0
1             Cloud Engineer          90000.0
2               Data Analyst          90000.0
0           Business Analyst          85000.0

In [22]:
df.loc[df["salary_year_avg"].notna()][["job_title_short", "job_country", "salary_year_avg"]].sort_values(by="salary_year_avg", ascending=False)

              job_title_short    job_country  salary_year_avg
554784         Data Scientist  United States         960000.0
665811  Senior Data Scientist   South Africa         890000.0
168402           Data Analyst          India         650000.0
387378         Data Scientist  United States         585000.0
160521         Data Scientist          Sudan         550000.0
...                       ...            ...              ...
213687          Data Engineer       Pakistan          24000.0
535260          Data Engineer  United States          23496.0
130855          Data Engineer      Australia          20000.0
380187       Business Analyst     Bangladesh          16500.0
665729          Data Engineer         Brazil          15000.0

[22003 rows x 3 columns]

In [31]:
# group by parameter is the column that the data will be grouped by, and .agg receives the name of the aggregation column, the numeric column and the calculation
df.groupby("job_title_short").agg(
    median_yearly_salary=("salary_year_avg", "median")
).reset_index().sort_values(by="median_yearly_salary", ascending=False)

             job_title_short  median_yearly_salary
8      Senior Data Scientist              155500.0
7       Senior Data Engineer              147500.0
4             Data Scientist              127500.0
3              Data Engineer              125000.0
6        Senior Data Analyst              111175.0
5  Machine Learning Engineer              106415.0
9          Software Engineer               99150.0
1             Cloud Engineer               90000.0
2               Data Analyst               90000.0
0           Business Analyst               85000.0

In [40]:
aggregation = df.groupby("job_title_short").agg(
    avg_yearly_salary=("salary_year_avg", "mean")
).reset_index()

In [44]:
aggregation.sort_values(by="avg_yearly_salary", ascending=False).round(2)

             job_title_short  avg_yearly_salary
8      Senior Data Scientist          154206.29
7       Senior Data Engineer          145840.61
4             Data Scientist          135988.84
3              Data Engineer          130125.60
5  Machine Learning Engineer          126774.32
6        Senior Data Analyst          113911.36
9          Software Engineer          113393.76
1             Cloud Engineer          111268.45
2               Data Analyst           93841.91
0           Business Analyst           91082.61