In [1]:
import pandas as pd
from datasets import load_dataset

# data load
ds = load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()

# data clean
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

c:\Users\Felipe Novais\.conda\envs\data_jobs\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
# Filtering data from salary_year_avg column

df.loc[
    df["salary_year_avg"].notna(),
    "salary_year_avg"
]

## .apply() method - utilized to apply functions to rows and columns of a DataFrame

In [17]:
# basic test without the .apply() method

salaries = df.loc[
    df["salary_year_avg"].notna(),
    ["job_title_short", "company_name","salary_year_avg"]
].reset_index(drop=True).copy()

salaries["adjusted_salary_1"] = salaries["salary_year_avg"] * 1.03 # inflation

salaries.head()

,job_title_short,company_name,salary_year_avg,adjusted_salary_1
0,Data Scientist,Netskope,109500.0,112785.00
1,Data Engineer,Intelletec,140000.0,144200.00
2,Data Engineer,Apex Systems,120000.0,123600.00
3,Data Scientist,TikTok,228222.0,235068.66
4,Data Analyst,Get It Recruit - Transportation,89000.0,91670.00

In [18]:
# creating a simple function to utilize the .apply() method

def salary_inflation(salary: float) -> float:
    return salary * 1.03

salaries["adjusted_salary_2"] = salaries["salary_year_avg"].apply(salary_inflation)

salaries.head()

,job_title_short,company_name,salary_year_avg,adjusted_salary_1,adjusted_salary_2
0,Data Scientist,Netskope,109500.0,112785.00,112785.00
1,Data Engineer,Intelletec,140000.0,144200.00,144200.00
2,Data Engineer,Apex Systems,120000.0,123600.00,123600.00
3,Data Scientist,TikTok,228222.0,235068.66,235068.66
4,Data Analyst,Get It Recruit - Transportation,89000.0,91670.00,91670.00

In [ ]:
# reseting the second column and utilizing a lambda function instead to create it

salaries.drop(columns=["adjusted_salary_2"], inplace=True)

In [22]:
salaries["adjusted_salary_2"] = salaries["salary_year_avg"].apply(lambda salary: salary * 1.03)
salaries.head()

,job_title_short,company_name,salary_year_avg,adjusted_salary_1,adjusted_salary_2
0,Data Scientist,Netskope,109500.0,112785.00,112785.00
1,Data Engineer,Intelletec,140000.0,144200.00,144200.00
2,Data Engineer,Apex Systems,120000.0,123600.00,123600.00
3,Data Scientist,TikTok,228222.0,235068.66,235068.66
4,Data Analyst,Get It Recruit - Transportation,89000.0,91670.00,91670.00

In [28]:
# checking job_skills column data type

type(df.loc[
    500,
    "job_skills"
])

str

In [30]:
df.loc[
    500,
    "job_skills"
]

"['t-sql', 'sql', 'sql server', 'aws', 'azure', 'snowflake', 'ssis']"

In [33]:
import ast

list_string_test = "['Felipe', 'Maria', 'Gustavo']"
list_string_converted = ast.literal_eval(list_string_test)
print(list_string_converted, type(list_string_converted))

['Felipe', 'Maria', 'Gustavo'] <class 'list'>

In [40]:
def convert_str_to_list(job_skills: str) -> list:
    if pd.isna(job_skills):
        return job_skills
    else:
        return ast.literal_eval(job_skills)
    
df["job_skills"] = df["job_skills"].apply(convert_str_to_list)

## Utilizing the .apply() method on rows with axis=1

In [56]:
# specifying the column in not necessary because the function will be applied on a row level, not column

def salary_inflation_2(row: pd.Series) -> pd.Series:
    if "Senior" in row["job_title_short"]:
        return row["salary_year_avg"] * 1.05
    else:
        return row["salary_year_avg"] * 1.03
    
salaries["adjusted_salary_3"] = salaries.apply(salary_inflation_2, axis=1)

salaries.loc[
    salaries["job_title_short"].str.contains("Senior"),
    :
]

,job_title_short,company_name,salary_year_avg,adjusted_salary_1,adjusted_salary_2,adjusted_salary_3
16,Senior Data Engineer,hackajob,168500.0,173555.000,173555.000,176925.000
20,Senior Data Engineer,Crackajack Solutions,160000.0,164800.000,164800.000,168000.000
23,Senior Data Engineer,Coda Search│Staffing,165000.0,169950.000,169950.000,173250.000
27,Senior Data Engineer,Capital One,173500.0,178705.000,178705.000,182175.000
28,Senior Data Engineer,X4 Life Sciences,160000.0,164800.000,164800.000,168000.000
...,...,...,...,...,...,...
21985,Senior Data Engineer,Harnham,150000.0,154500.000,154500.000,157500.000
21986,Senior Data Engineer,Athletic Greens,125000.0,128750.000,128750.000,131250.000
21987,Senior Data Scientist,Arthur Grand Technologies Inc,99150.0,102124.500,102124.500,104107.500
21992,Senior Data Scientist,TikTok,200935.5,206963.565,206963.565,210982.275
21993,Senior Data Scientist,TikTok,196800.0,202704.000,202704.000,206640.000

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), object(1), str(10)
memory usage: 232.2+ MB

In [49]:
salaries.info()

<class 'pandas.DataFrame'>
RangeIndex: 22003 entries, 0 to 22002
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   job_title_short    22003 non-null  str
 1   company_name       22003 non-null  str
 2   salary_year_avg    22003 non-null  float64
 3   adjusted_salary_1  22003 non-null  float64
 4   adjusted_salary_2  22003 non-null  float64
dtypes: float64(3), str(2)
memory usage: 1.5 MB