In [1]:
import pandas as pd
from datasets import load_dataset

# load data
ds = load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()

# convert date column do datetime
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

c:\Users\Felipe Novais\.conda\envs\data_jobs\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
# iloc usage example

df.iloc[
    0:8,
    0:6
]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True

In [8]:
# loc usage example 1

df.loc[
    :,
    ["job_title_short", "company_name", "job_country", "salary_year_avg"]
]

,job_title_short,company_name,job_country,salary_year_avg
0,Senior Data Engineer,Boehringer Ingelheim,United States,NaN
1,Data Analyst,Hewlett Packard Enterprise,Mexico,NaN
2,Data Engineer,ALPHA Augmented Services,Germany,NaN
3,Data Engineer,Southwest Research Institute,United States,NaN
4,Data Engineer,Kristina Daniel,Sudan,NaN
...,...,...,...,...
785736,Software Engineer,CAREERSTAR INTERNATIONAL PTE. LTD.,Singapore,NaN
785737,Data Analyst,HABA FAMILYGROUP,Germany,NaN
785738,Business Analyst,Lendlease Corporation,Malaysia,NaN
785739,Data Engineer,Capital One,Sudan,NaN
785740,Software Engineer,Trigyn,India,NaN

In [27]:
# loc usage example 2

df.loc[
    df["salary_year_avg"].notna(),
    ["job_title_short", "company_name", "job_country", "salary_year_avg"]
].reset_index(drop=True)

,job_title_short,company_name,job_country,salary_year_avg
0,Data Scientist,Netskope,Costa Rica,109500.0
1,Data Engineer,Intelletec,Sudan,140000.0
2,Data Engineer,Apex Systems,United States,120000.0
3,Data Scientist,TikTok,United States,228222.0
4,Data Analyst,Get It Recruit - Transportation,United States,89000.0
...,...,...,...,...
21998,Data Engineer,Bosch Group,United States,139216.0
21999,Data Engineer,"Engage Partners, Inc.",United States,150000.0
22000,Data Scientist,84.51°,United States,221875.0
22001,Data Scientist,Bosch Group,Germany,157500.0
22002,Data Scientist,Tenet3,United States,157500.0

In [28]:
# loc usage example 3

df.loc[
    :,
    ["job_title_short", "company_name", "job_country", "salary_year_avg"]
].dropna(subset="salary_year_avg").sort_values(by="salary_year_avg", ascending=False).reset_index(drop=True)

,job_title_short,company_name,job_country,salary_year_avg
0,Data Scientist,"East River Electric Power Cooperative, Inc.",United States,960000.0
1,Senior Data Scientist,MSP Staffing LTD,South Africa,890000.0
2,Data Analyst,Mantys,India,650000.0
3,Data Scientist,ReServe,United States,585000.0
4,Data Scientist,Selby Jennings,Sudan,550000.0
...,...,...,...,...
21998,Data Engineer,Flipdish,Pakistan,24000.0
21999,Data Engineer,American Century Investments,United States,23496.0
22000,Data Engineer,Showwcase,Australia,20000.0
22001,Business Analyst,Forward,Bangladesh,16500.0
22002,Data Engineer,Net2Source Inc.,Brazil,15000.0

In [29]:
# loc usage example 4

df.loc[
    (df["salary_year_avg"].notna()) & (df["job_country"] == "Brazil"),
    ["job_title_short", "company_name", "job_country", "salary_year_avg"]
].sort_values(by="salary_year_avg", ascending=False).reset_index(drop=True)

              job_title_short       company_name job_country  salary_year_avg
0        Senior Data Engineer            MongoDB      Brazil         224000.0
1        Senior Data Engineer            MongoDB      Brazil         224000.0
2           Software Engineer            MongoDB      Brazil         200000.0
3              Data Scientist            MongoDB      Brazil         197500.0
4              Data Scientist               Visa      Brazil         196000.0
..                        ...                ...         ...              ...
56               Data Analyst          Riskified      Brazil          53014.0
57               Data Analyst  Turner & Townsend      Brazil          50400.0
58               Data Analyst            Gympass      Brazil          50400.0
59  Machine Learning Engineer           Experian      Brazil          50400.0
60              Data Engineer    Net2Source Inc.      Brazil          15000.0

[61 rows x 4 columns]

In [35]:
# loc usage example 5

df.loc[
    (df["salary_year_avg"].notna()) & (df["job_country"] == "India") & (df["job_title_short"].str.contains("Senior")),
    ["job_title_short", "company_name", "job_country", "salary_year_avg"]
].sort_values(by="salary_year_avg", ascending=False).reset_index(drop=True)

           job_title_short          company_name job_country  salary_year_avg
0     Senior Data Engineer  Bristol Myers Squibb       India         181765.0
1      Senior Data Analyst                Verisk       India         177283.0
2    Senior Data Scientist               Equifax       India         170575.0
3    Senior Data Scientist             Deliveroo       India         170500.0
4    Senior Data Scientist               Cargill       India         170000.0
..                     ...                   ...         ...              ...
112    Senior Data Analyst       Publicis Groupe       India          64800.0
113   Senior Data Engineer           Exceptionly       India          56000.0
114   Senior Data Engineer               Nielsen       India          45000.0
115   Senior Data Engineer                  Skan       India          45000.0
116   Senior Data Engineer    Dforth Technlogies       India          35000.0

[117 rows x 4 columns]

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB