In [1]:
import pandas as pd
from datasets import load_dataset

# load data
ds = load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()

# clean data
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

c:\Users\Felipe Novais\.conda\envs\data_jobs\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
print(f"Unaltered dataframe total rows: {len(df)}")

Unaltered dataframe total rows: 785741

In [5]:
# data cleaning step 1: remove all around duplicates

df_duplicates_removed_1 = df.drop_duplicates()

print(f"Unaltered dataframe total rows: {len(df)}")
print(f"Duplicates removed dataframe total rows: {len(df_duplicates_removed_1)}")
print(f"Total duplicates removed: {len(df) - len(df_duplicates_removed_1)}")

Unaltered dataframe total rows: 785741
Duplicates removed dataframe total rows: 785640
Total duplicates removed: 101

In [13]:
# data cleaning step 2: remove duplicates based on a subset, repeated job titles from the same company

df_duplicates_removed_2 = df.drop_duplicates(subset=["job_title", "company_name"])

print(f"Unaltered dataframe total rows: {len(df)}")
print(f"Duplicates removed dataframe total rows: {len(df_duplicates_removed_2)}")
print(f"Total duplicates removed: {len(df) - len(df_duplicates_removed_2)}")

Unaltered dataframe total rows: 785741
Duplicates removed dataframe total rows: 508042
Total duplicates removed: 277699

In [14]:
# data cleaning step 3: replace NaN values from salary columns with their median counterparts

median_yearly_salary = df["salary_year_avg"].median()
median_hourly_salary = df["salary_hour_avg"].median()

df_duplicates_removed_2.loc[:, ["salary_year_avg", "salary_hour_avg"]].head()

   salary_year_avg  salary_hour_avg
0              NaN              NaN
1              NaN              NaN
2              NaN              NaN
3              NaN              NaN
4              NaN              NaN

In [15]:
df_fillna = df_duplicates_removed_2

df_fillna["salary_year_avg"] = df_duplicates_removed_2["salary_year_avg"].fillna(median_yearly_salary)
df_fillna["salary_hour_avg"] = df_duplicates_removed_2["salary_hour_avg"].fillna(median_hourly_salary)

df_fillna.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,115000.0,45.98,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,115000.0,45.98,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,115000.0,45.98,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,115000.0,45.98,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,115000.0,45.98,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB