In [ ]:
import pandas as pd
from datasets import load_dataset

# load data
ds = load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()

# clean data
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

In [2]:
# the .head() method does not return a true sample of the data

df.head(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."

In [ ]:
# the .sample() method is much better, as it provides random rows from the dataframe for better analysis

df.sample(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
148207,Business Analyst,Insurance Analyst,"Warsaw, Poland",via LinkedIn,Full-time,False,Poland,2023-08-05 09:15:48,False,False,Poland,NaN,NaN,NaN,Avon,"['excel', 'powerpoint', 'word']","{'analyst_tools': ['excel', 'powerpoint', 'wor..."
288509,Data Scientist,IDOH Data Scientist,"New York, NY",via GrabJobs,Full-time,False,"New York, United States",2023-11-18 17:01:41,False,False,United States,NaN,NaN,NaN,Infostretch Corporation,NaN,NaN
247101,Senior Data Scientist,Senior Data Scientist,"Atlanta, GA",via LinkedIn,Part-time,False,"Florida, United States",2023-02-03 07:08:15,False,True,United States,NaN,NaN,NaN,TechFetch.com - On Demand Tech Workforce hirin...,"['sql', 'python', 'oracle', 'tensorflow', 'ker...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."

In [11]:
# utilize random_state to return always the same sample result

df.sample(3, random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN

In [ ]:
# to create copies of dataframes, it is better to utilize the .copy() method, as the equal sign does not create a new dataframe

df_test_1 = df

print(id(df))
print(id(df_test_1))
print("are the IDs equal?", "Yes" if id(df) == id(df_test_1) else "No")

2420955324320
2420955324320
are the IDs equal? Yes

In [15]:
# .copy() method example

df_test_2 = df.copy()

print(id(df))
print(id(df_test_2))
print("are the IDs equal?", "Yes" if id(df) == id(df_test_2) else "No")

2420955324320
2420955321248
are the IDs equal? No