In [ ]:
import pandas as pd
from datasets import load_dataset

# load data
ds = load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()

# clean data
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

## Concat Example 1 (SQL Union)

In [2]:
# example data
job_postings_jan = pd.DataFrame({
    "job_id":[1, 2, 3, 4, 5],
    "job_title":["Data Scientist", "Data Analyst", "Machine Learning Engineer", "Data Scientist", "Data Engineer"],
    "company":["Company A", "Company B", "Company C", "Company D", "Company E"],
    "job_posted_date":["2024-01-02", "2024-01-07", "2024-01-14", "2024-01-19", "2024-01-24"]
})

job_postings_feb = pd.DataFrame({
    "job_id":[6, 7, 8, 9, 10],
    "job_title":["Data Scientist", "Data Analyst", "Machine Learning Engineer", "Data Scientist", "Data Engineer"],
    "company":["Company F", "Company G", "Company H", "Company I", "Company J"],
    "job_posted_date":["2024-02-05", "2024-02-09", "2024-02-12", "2024-02-18", "2024-02-22"]
})

In [ ]:
# example 1
pd.concat(objs=[job_postings_jan, job_postings_feb], ignore_index=True)

   job_id                  job_title    company job_posted_date
0       1             Data Scientist  Company A      2024-01-02
1       2               Data Analyst  Company B      2024-01-07
2       3  Machine Learning Engineer  Company C      2024-01-14
3       4             Data Scientist  Company D      2024-01-19
4       5              Data Engineer  Company E      2024-01-24
5       6             Data Scientist  Company F      2024-02-05
6       7               Data Analyst  Company G      2024-02-09
7       8  Machine Learning Engineer  Company H      2024-02-12
8       9             Data Scientist  Company I      2024-02-18
9      10              Data Engineer  Company J      2024-02-22

In [11]:
# example 2
example_df = pd.concat(objs=[job_postings_jan, job_postings_feb]).set_index("job_id")
example_df["job_posted_date"] = pd.to_datetime(example_df["job_posted_date"])

example_df

                        job_title    company job_posted_date
job_id
1                  Data Scientist  Company A      2024-01-02
2                    Data Analyst  Company B      2024-01-07
3       Machine Learning Engineer  Company C      2024-01-14
4                  Data Scientist  Company D      2024-01-19
5                   Data Engineer  Company E      2024-01-24
6                  Data Scientist  Company F      2024-02-05
7                    Data Analyst  Company G      2024-02-09
8       Machine Learning Engineer  Company H      2024-02-12
9                  Data Scientist  Company I      2024-02-18
10                  Data Engineer  Company J      2024-02-22

## Concat Example 2 (SQL Union)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [ ]:
# separating dataframes based on months

df["job_posted_month"] = df["job_posted_date"].dt.strftime("%b")
months = df["job_posted_month"].unique()

dict_months = {month:df.loc[df["job_posted_month"] == month, :] for month in months}

Jun
Jan
Oct
Jul
Aug
Nov
Mar
Dec
Apr
Feb
Sep
May

In [30]:
# retrieving data from 2023 first quarter

first_quarter_df = pd.concat(objs=[dict_months["Jan"], dict_months["Feb"], dict_months["Mar"]]).reset_index(drop=True)
first_quarter_df.drop(columns="job_posted_month", inplace=True)

first_quarter_df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
1,Data Scientist,Data Scientist,"Zaventem, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-31 13:53:38,False,False,Belgium,NaN,NaN,NaN,Devoteam,"['r', 'python', 'sql', 'pandas', 'numpy', 'sci...","{'libraries': ['pandas', 'numpy', 'scikit-lear..."
2,Data Engineer,Data Engineer,"Fort Worth, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-25 13:24:01,False,False,United States,NaN,NaN,NaN,Programmers.io,"['sql', 'python']","{'programming': ['sql', 'python']}"
3,Data Engineer,Data Engineer,"San Mateo, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-28 13:07:30,False,True,United States,NaN,NaN,NaN,Verkada,"['sql', 'python', 'aws', 'looker']","{'analyst_tools': ['looker'], 'cloud': ['aws']..."
4,Data Scientist,Data Scientist,"São Paulo, State of São Paulo, Brazil",via BeBee,Full-time,False,Brazil,2023-01-03 23:02:27,False,False,Brazil,NaN,NaN,NaN,Mars,"['python', 'sql', 'azure']","{'cloud': ['azure'], 'programming': ['python',..."

Merge (SQL Join) is a method, and Concat (SQL Union) is a function